travis:
  secure:
    BINSTAR_TOKEN: PxFWw3oTH1M1P+LSetiBjbJGHga7RyRJXg4aP9gtUNKBWMR5SENf8OmiQ1fXY6XaO2J8mP0w8eUK4B/WIX+KWpCEUz0b0BLm1hq24aPctwFKck2wxrVy5RTd6QDjh/FFlCiEr8o6R7PRS+hMnp4xHpfHRmP7i521inp05G8S+90VHURcVGvLyyxQ0EwBFzC98obtmqwGPmmRXA6xVq5eMfylig21C5gDd1LwAzuOOmY+LhmckYlxfX+GXEbQPyJtQiugQpLemu/hvJ/s2WNd7WnMVD+swq1WqPeAlfNavCnFubLOHkmfuCsPabwLqYKiUH4/fugvfcx8SwrzgVIv2rKpeXNVreCzo2brHv9xdOaSFFvQgQyV3+08K57AzXidHw0nvhAqy3F6Z1dhoVYkk4rn/1hmPdmUdaXWWkvnDIj42XJMhS1oMA84mVvKxEdASHTJ1xYWin8962MoHek8qNglNRdmAaGnV2vS+RAjVyuCSsmmCe/FgNZe5Tgwx/GvQlzdYGYqzEsxit1Ex0i0PY2iogpfrJF7i1G3RjcCjfUE6slRBj+6SMYtDIMC5ivQjoEceC1/SidoLn+HvDTdLqe8zdfmPcFWnKY/jdRE/L5HHubKF/l2ZPsU3kqVCC8hnh9QDCdUgx71o+ax0e+PSdsQyjt66twLIICM6Xq3muc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
