travis:
  secure:
    BINSTAR_TOKEN: YYzerenGAY1Zz8gvJ+nzf59Sc36Sx+EDPpscDEzR48hYVQpziChXogOf0X35Aq5KJMY+YAQ1kpCUylJ2kYQ0RS6tArbROTBiWy5q9uJxAexMIMfW2RirShqIsZU+8xlEfBePluJPn15O8MrkhVYaXef6R9ThCboHbZD2nEHrpqEpnzMNmuRj6jP7dvADBYowBBxum3TVKmAEZ7zrI0qGpWSy9EMApCmLK5W9MI6YyysaqxGvenaCbCEbbRJlV5oC/vrfg3zK30DIW0aZiAXG+Me/zqnSBnTLLogp7pf98Dy+H6UzETB7GNqALivaQXIHvwLRxuCUsR0RljcGJnm7Yy1L0WuCk9Gsxj3D4Ilv99LHV2RqN7stNZ7+RYm1M7OB6MHYXGpHfnRHXzks4tyKgPVCqw7kOLJ5s6vh44WqrnC1zrFGVHKcLtTsp/NSq6fFV8BpmMDikAax9ciKzDlTCtfFXZ5cztMLA/ZfN4i5QuM1TXGOqlwQLx23oAik3OSWi5Lj/4673hjfZyvsiVhgZoYyB3TZYxjgiO2SCrjoTWs1Ys/bhFNiuWlMlUJX5Jv4UBaTgYxgyGtjxoqU/2Sr6mJQVfO5n281Wp6CiDOEl0Xal1ZzdKTa8Wo/n6jcU6irNVa76mj1NY4AUy6ADshEQVfOjgYy8kr/KJyzRiI8zw8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
